name: PTT Telegram Notify

on:
  schedule:
    - cron: '*/3 * * * *'  # 每5分鐘執行一次
  workflow_dispatch:      # 允許手動執行

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run PTT Telegram Notify
        env:
          BOT_TOKEN: ${{ secrets.8482553745:AAHM7PxZNJg9j7ot7u88nAqJURchOSAnNp8 }}
          CHAT_ID: ${{ secrets.7701043479 }}
        run: |
          python ptt_telegram_notify.py
